### ISSUE TITLE
refactor transforms of response representations in the GetInfoResponseFixture into methods

### ISSUE THREAD

**Issue by zancas** [dannasessha/quizface#1]
Per this comment https://github.com/zingolabs/quizface/pull/12 we can refactor this code to have representation-generating methods.    I'm not certain it's significantly better, but as a pedagogical exercise, it'd be neat if @dannasessha worked through the refactor:   https://github.com/zingolabs/quizface/pull/12#discussion_r531671011

**Comment by dannasessha** [comment]
Stale, closing.
